# Generated by Django 3.1.2 on 2020-11-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Email', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=64)),
                ('Position', models.CharField(max_length=64)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
